apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: {{ .Values.admin.image }}
          ports:
            - containerPort: {{ .Values.admin.port }}
