replicaCount: 1

apiGateway:
  image: duonghung171204/api-gateway-v1
  port: 8000

frontend:
  image: duonghung171204/vuonlanho-frontend:v1.0.1-04092025-08-16-11
  port: 80

backend:
  image: duonghung171204/vuonlanho-backend:v1.0.4-05092025-09-25-34
  port: 4000
  env:
    - name: MONGODB_URI
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: MONGODB_URI
    - name: GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: oauth-secret
          key: GOOGLE_CLIENT_ID
    - name: GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: oauth-secret
          key: GOOGLE_CLIENT_SECRET
    - name: FACEBOOK_APP_ID
      valueFrom:
        secretKeyRef:
          name: facebook-secret
          key: FACEBOOK_APP_ID
    - name: FACEBOOK_APP_SECRET
      valueFrom:
        secretKeyRef:
          name: facebook-secret
          key: FACEBOOK_APP_SECRET
admin:
  image: duonghung171204/vuonlanho-admin:v1.0.2-29082025-09-54-10
  port: 80

mongodb:
  image: mongo:latest
  port: 27017
  storage: 5Gi
