replicaCount: 1

apiGateway:
  image: duonghung171204/api-gateway-v1
  port: 8000

frontend:
  image: duonghung171204/vuonlanho-frontend:v1.0.1-04092025-08-16-11
  port: 80

backend:
  image: duonghung171204/vuonlanho-backend:v1.0.2-04092025-08-16-11
  port: 4000
  env:
    - name: MONGO_URI
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: MONGO_URI

admin:
  image: duonghung171204/vuonlanho-admin:v1.0.2-29082025-09-54-10
  port: 80

mongodb:
  image: mongo:latest
  port: 27017
  storage: 5Gi
